### ISSUE TITLE
ember-a11y-testing make a few things scroll at the bottom of the page.

### ISSUE THREAD

**Issue by AdrienNguyenWorldline** [ember-a11y/ember-a11y-testing#77] opened 2017-04-07 14:48 UTC
If I leave the plugin active, when I click on some actions, I get no error in console at all, nor stiped elements, but the page scrolls at the bottom.

If I just add `turnAuditOff: true,` then this scrolling bugs goes away

**Comment by trentmwillis** [comment] 2017-04-09 00:15
Can you provide a reproduction either via ember-twiddle or a github repo? This addon doesn't do anything directly related to scrolling.

**Comment by justwright** [comment] 2017-05-02 22:25
I think this may be related to scrolling issues within axe-core

https://github.com/dequelabs/axe-core/pull/148

**Comment by ctcpip** [comment] 2017-05-18 21:59
Not sure if the exact same issue, but I observe this as well.  It is automatically scrolling to the last ember component on the page.

**Comment by ctcpip** [comment] 2017-05-31 14:40
The axe-core issue mentioned above has been fixed & merged and does not resolve this issue.

Another situation that easily reproduces the issue (and it's even worse):  I am displaying a relative time - example: '3 seconds ago', '10 seconds ago', etc.  This value is updated every second, and every time it is updated, `ember-a11y-testing` scrolls to its position.  It even happens when the text doesn't even change - for example, it simply shows '3 minutes ago' for an entire minute, but nonetheless `ember-a11y-testing` scrolls to this line every second. Very frustrating.  `turnAuditOff` does prevent the behavior, but that somewhat defeats the purpose of using this addon.

**Comment by ctcpip** [comment] 2017-05-31 14:49
```
Ember      : 2.13.0
Ember Data : 2.13.1
jQuery     : 3.2.1
```

**Comment by dylanb** [comment] 2017-05-31 15:01
to fix this issue, you need to pass in the `noScroll` option to the `color-contrast` rule

**Comment by ctcpip** [comment] 2017-05-31 16:00
@dylanb Thanks for that tip!  Can confirm that it works.  It took me a while to figure out the right syntax... the `axe-core` docs were not very helpful.  Here it is:

```
  ENV['ember-a11y-testing'] = {
    componentOptions: {
      axeOptions: {
        checks: {
          'color-contrast': { options: { noScroll: true } }
        }
      }
    }
  };
```

**Comment by ctcpip** [comment] 2017-05-31 16:01
@trentmwillis I suggest this option be set by default within this addon if possible...  this made me pull my hair out, and I think others will have the same experience...  I don't think this scrolling is a desirable default behavior.  Thoughts?

**Comment by trentmwillis** [comment] 2017-06-01 01:19
Currently, we leave the defaults to `axe-core`, so if this is the default for that library I'd prefer not to change it.

That said, we can call it out in our documentation and definitely should make it easier for folks to figure out how to set options. Would you mind PR'ing some doc changes to help clarify areas you had trouble with?

**Comment by dylanb** [comment] 2017-06-01 04:36
@ctcpip we have to leave at least a bit of a challenge for the users ;-)

But srsly - if you have a suggestion for a doc change, please contribute...

**Comment by ctcpip** [comment] 2017-06-08 19:41
I could take a stab at something, but I'm not entirely clear on how the options should really be specified.  What I ended up with works, but it involved me stepping through the code while it was running, and scrutinizing the axe-core codebase...

**Comment by trentmwillis** [comment] 2017-06-22 03:09
Since we now have an example in the readme of how to [set options for specific rules](https://github.com/ember-a11y/ember-a11y-testing#environment-options), I'm going to close this.

**Closed by trentmwillis** 2017-06-22 03:09 UTC

**Comment by kundankeshri** [comment] 2018-10-10 04:47
I set "restoreScroll" : true and its working fine for me
