### ISSUE TITLE
Uncaught Error: Could not find module `@babel/runtime/helpers/esm/classCallCheck`

### ISSUE THREAD

**Issue by jackson-dean** [ember-a11y/ember-a11y-testing#126] opened 2019-05-11 03:35 UTC
Getting this error immediately after installing the addon

**Comment by drewlee** [comment] 2019-10-10 22:52
Doesn't seem to be related to the addon. @jackson-dean, can you confirm if you're still seeing this error? If so, please provide guidance on how to reproduce.

**Comment by jackson-dean** [comment] 2019-10-14 21:49
@drewlee ahh, yes, i don't know what happened there, but it seemed to be working fine after re-installing everything. forgot to update this. but seems fine now.

**Comment by drewlee** [comment] 2019-10-14 23:54
Thanks for following up, @jackson-dean. Closing as cannot reproduce.

**Closed** 2019-10-14 23:55 UTC
